### ISSUE TITLE
Basics feedback

### ISSUE THREAD

**Issue by yevagorbachev** [RIT-Launch-Initiative/Liftoff-Project#2]
- Clarify "the flag for handling includes". To someone who has never used that flag, this means nothing. You can say this more descriptively, by stating how the compiler figures out where the things you told it to #include are
- Clarify "if you truly feel comfortable writing ..." to include build automation, I think it's plausible someone's comfortable with the language but not Makefiles
- You say "I recommend understanding how Makefiles work." Be a bit more specific (see general advice)
- Comment on that there seem to be (at least as far as I see) two levels - there are manual makefiles where you specify every target and dependency, but the makefile generated by STM32CubeIDE uses wildcards pretty extensively, so those seem worth learning (or at least saying the exist)

**Comment by AarC10** [comment]
Done
