### ISSUE TITLE
Memory and Bits feedback

### ISSUE THREAD

**Issue by yevagorbachev** [RIT-Launch-Initiative/Liftoff-Project#3]
- Memory and Bits
- I like the discouragement from using static allocation
- Comment somewhere on endianness
- I'm not sure about statics being accessible from "anywhere in the code", I would maybe specify that this is "inside the source file currently being compiled" (unless you extern it? Will question)
- The word "masks" is used a lot (doing ops on bits in registers, the "subnet mask" in IP), so you should briefly define and describe what docs usually mean when they say "mask" (maybe have a couple of examples)
- "I don't feel like typing" is an awful reason to do anything, don't include that part (sets a bad example)
- Define "buffer" somewhere, and say how they're used (e.g. passed around as a pointer and its `len`)

**Comment by AarC10** [comment]
I was trolling with the I dont feel like typing :) but yea fair enough

For the static part, this is why I mentioned it means different things under different contexts. Was a little more specific and added two extra links to talk about this. You're right on anywhere in code, meant to say anywhere in file. static variables and functions that are file scoped should not be accessible outside the file.  

Rest of the stuff you want added was good and added in
