### ISSUE TITLE
Embedded systems

### ISSUE THREAD

**Issue by yevagorbachev** [RIT-Launch-Initiative/Liftoff-Project#4]
- As is, it really just talks about using communication protocols. I would rename this to something like "Communicating with peripherals"
- Be a bit more verbose in "API for controlling the hardware" (e.g. say something like "You don't need to know how to generate a clock signal or send bytes down the interface, the function will take from you a buffer and handle it for you"
- Define what the abbreviations "SDA, SCL, MOSI, MISO" mean (unless you want to check that noobs will do basic googling - fair enough)
- SPI lines are also called CIPO, COPI for "Controller out, Peripheral in"

**Comment by AarC10** [comment]
Going to skip the CIPO and COPI abbreviations. I am mostly going off of what is common terminology in the peripherals we currently use. Only seen DO/DI and MISO/MOSI. If it becomes a lot more common in the future we can add it in

Updated first two bullets. Added some additional resources links including one on pin abbreviations
